project:
  name: camunda-workflow
  author:
    name: MUHAMUHA
    email: 2472350821@qq.com
  version: v1

camunda:
  bpm:
#    启动创建表
#    filter:
#      create: All tasks

server:
  port: 8089
  servlet:
    context-path: /camunda-flow/v1

spring:
  datasource:
    ds1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.36.194.82:8081/camunda_workflow?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false&characterEncoding=UTF-8
#      username: wzkbbase
#      password: SudpHfAcz_@OW&Ik
      url: jdbc:mysql://localhost:3307/camunda_workflow?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false
      username: root
      password: 1234
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.wzxc.camunda.dao: debug



