server:
  port: 8888
  servlet:
    context-path: /zzdPush

spring:
  # DataSource
  datasource:
    ds1: # 数据源1 - 信产服务器
      name: ds1
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.36.198.152:3307/zzd?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false
      username: root
      password: AGyisY9scF6BxpgwQRKykatqD5VDHYnG
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
    ds2: # 数据源2 - 城市大脑服务器 - 开发服务器
      name: ds2
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.36.211.129:8306/wz_digital_cockpit?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false
      username: zhuzp
      password: u34dsafgkhgsg
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

zzd:
  config:
    appkey: cityb-id782eOcRN5n4j0GQkBRVvYv
    secret: 1PZi8U75I4K4htJ2CWFlE2dL7419Ei29f5xt4VuK
    tenantid: 50162234
    domain-name: openplatform.dg-work.cn
    protocal: https
    msgApp: cityb