server:
  port: 10005
  servlet:
    context-path: /zzdPush

spring:
  datasource:
    ds1: # 数据源1 - 信产服务器
      name: ds1
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.36.198.152:3307/zzd?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false
      username: root
      password: AGyisY9scF6BxpgwQRKykatqD5VDHYnG
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
    ds3: # 数据源3 - 城市大脑服务器
      name: ds3
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.12.74:3306/wz_digital_cockpit?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false
      username: zhuzp
      password: u34dsafgkhgsg
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

zzd:
  config:
    appkey: CityBMessage-QF83wtt3vTdQnIzQ3
    secret: 7gGV92Gs50W7zKVts0Ys4Ni5z4tUZ28l2fQrF3rT
    tenantid: 196729
    domain-name: openplatform-pro.ding.zj.gov.cn
    protocal: https
    msgApp: CityBMessage